FROM node:20 AS Build
WORKDIR /opt/server
COPY package.json . 
COPY *.js .
RUN apt inatall


FROM node:20.18.0
EXPOSE 8080
ENV DB_HOST="my_sql"
RUN addgroup -S expence && adduser -S expence -G expence && \
    mkdir /opt/server && \
    chown -R expence:expence /opt/server
WORKDIR /opt/server
COPY --from=Build /opt/server /opt/server/
USER expence
CMD [ "node", "index.js" ]